image: node:lts

before_script:
    - apt-get update -qq && apt-get install -y -qq npm
    - npm install
pages:
  script: 
        - npm run build
        - cp -r dist/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
